#lang sicp

(#%require rackunit)

;;; Exercise 1.14, page 44

;; Draw the tree illustrating the process generated by the count-change
;; procedure of section 1.2.2 in making change for 11 cents. What are
;; the orders of growth of the space and number of steps used by this
;; process as the amount to be changed increases?

;; see page 41 or change.rkt for an implementation of the algorithm

;; ignoring visual answers PlantUML or LaTeX+TiKZ solution is done

