;;; Exercise 1.14 page 44

;; Draw the tree illustrating the process generated by the count-change
;; procedure of section 1.2.2 in making change for 11 cents. What are the
;; orders of growth of the space and number of steps used by this process as
;; the amount to be changed increases?

;; Consider a drawing in LaTeX with TikZ or something similar? I can't really
;; draw a tree here.
